Conceccion con MySQL Workbench

In [1]:
import mysql.connector

# Configurar los detalles de la conexión
config = {
    'user': 'root',
    'password': 'root',
    'host': 'localhost',
    'database': 'candidates'
}

Insertar el Dataset en la tabla creada en MySQL Workbench ** No Ejecutar Mas **

In [ ]:
import mysql.connector
import pandas as pd

# Configurar los detalles de la conexión
config = {
    'user': 'root',
    'password': 'root',
    'host': 'localhost',
    'database': 'candidates'
}

# Conectar a la base de datos
db_connection = mysql.connector.connect(**config)
cursor = db_connection.cursor()

# Ruta al archivo CSV
csv_file_path = r'C:\Users\josed\OneDrive\Documentos\UNIVERSIDAD\ETL\WORKSHOP 1 - JOSE CARRERA\candidates.csv'

# Leer el archivo CSV en un DataFrame de pandas
candidates_data = pd.read_csv(csv_file_path, delimiter=';')

# Verificar los nombres de las columnas
print(candidates_data.columns)

# Asegurarse de usar los nombres correctos de las columnas
candidates_data['Application Date'] = pd.to_datetime(candidates_data['Application Date'], errors='coerce').dt.strftime('%Y-%m-%d')
candidates_data['YOE'] = pd.to_numeric(candidates_data['YOE'], errors='coerce').fillna(0).astype(int)

# Insertar los datos del CSV en la tabla
for _, row in candidates_data.iterrows():
    cursor.execute("""
    INSERT INTO candidates (First_Name, Last_Name, Email, Country, Application_Date, YOE, Seniority, Technology, Code_Challenge_Score, Technical_Interview_Score)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['First Name'], 
        row['Last Name'], 
        row['Email'], 
        row['Country'], 
        row['Application Date'], 
        row['YOE'], 
        row['Seniority'], 
        row['Technology'], 
        row['Code Challenge Score'], 
        row['Technical Interview Score']
    ))

# Confirmar los cambios
db_connection.commit()

# Cerrar la conexión
cursor.close()
db_connection.close()

Coneccion con la tabla candidates

In [2]:
import pandas as pd

In [3]:
try:
    # Establecer la conexión
    connection = mysql.connector.connect(**config)
    print("Conexión exitosa a la base de datos")

    # Crear un cursor para ejecutar consultas
    cursor = connection.cursor()

    # Ejecutar la consulta para obtener datos
    query = "SELECT * FROM candidates"  # Reemplaza con tu consulta SQL
    cursor.execute(query)

    # Obtener los datos en un DataFrame de pandas
    df = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])

    print("Datos cargados en DataFrame:")
    print(df.head())

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("Conexión cerrada")

Conexión exitosa a la base de datos
Datos cargados en DataFrame:
   id  First_Name   Last_Name                      Email  Country  \
0   1  Bernadette   Langworth        leonard91@yahoo.com   Norway
1   2      Camryn    Reynolds        zelda56@hotmail.com   Panama
2   3       Larue      Spinka   okey_schultz41@gmail.com  Belarus
3   4        Arch      Spinka     elvera_kulas@yahoo.com  Eritrea
4   5       Larue  Altenwerth  minnie.gislason@gmail.com  Myanmar

  Application_Date  YOE  Seniority                         Technology  \
0       2021-02-26    2     Intern                      Data Engineer
1       2021-09-09   10     Intern                      Data Engineer
2       2020-04-14    4  Mid-Level                     Client Success
3       2020-10-01   25    Trainee                          QA Manual
4       2020-05-20   13  Mid-Level  Social Media Community Management

   Code_Challenge_Score  Technical_Interview_Score
0                   3.0                        3.0
1                   2.0                       10.0
2                  10.0                        9.0
3                   7.0                        1.0
4                   9.0                        7.0
Conexión cerrada

In [4]:
# Mostrar las primeras 10 filas
first_10_rows = df.head(10)
print("Primeras 10 filas:")
print(first_10_rows)

# Mostrar las últimas 10 filas
last_10_rows = df.tail(10)
print("Últimas 10 filas:")
print(last_10_rows)

# Construir un nuevo dataframe con los datos ordenados alfabéticamente por 'First Name' y 'Last Name'
sorted_df = df.sort_values(by=['First_Name', 'Last_Name'])

# Mostrar las primeras y últimas filas del dataframe ordenado
print("Primeras 10 filas ordenadas:")
print(sorted_df.head(10))

print("Últimas 10 filas ordenadas:")
print(sorted_df.tail(10))

Primeras 10 filas:
   id  First_Name   Last_Name                      Email            Country  \
0   1  Bernadette   Langworth        leonard91@yahoo.com             Norway
1   2      Camryn    Reynolds        zelda56@hotmail.com             Panama
2   3       Larue      Spinka   okey_schultz41@gmail.com            Belarus
3   4        Arch      Spinka     elvera_kulas@yahoo.com            Eritrea
4   5       Larue  Altenwerth  minnie.gislason@gmail.com            Myanmar
5   6        Alec      Abbott   juanita_hansen@gmail.com           Zimbabwe
6   7     Allison      Jacobs   alba_rolfson27@yahoo.com  Wallis and Futuna
7   8         Nya      Skiles   madisen.zulauf@gmail.com            Myanmar
8   9        Mose       Lakin   dale_murazik@hotmail.com              Italy
9  10    Terrance       Zieme       dustin31@hotmail.com        Timor-Leste

  Application_Date  YOE  Seniority                         Technology  \
0       2021-02-26    2     Intern                      Data Engineer
1       2021-09-09   10     Intern                      Data Engineer
2       2020-04-14    4  Mid-Level                     Client Success
3       2020-10-01   25    Trainee                          QA Manual
4       2020-05-20   13  Mid-Level  Social Media Community Management
5       2019-08-17    8     Junior           Adobe Experience Manager
6       2018-05-18   19    Trainee                              Sales
7       2021-12-09    1       Lead                           Mulesoft
8       2018-03-13   18       Lead  Social Media Community Management
9       2022-04-08   25       Lead                             DevOps

   Code_Challenge_Score  Technical_Interview_Score
0                   3.0                        3.0
1                   2.0                       10.0
2                  10.0                        9.0
3                   7.0                        1.0
4                   9.0                        7.0
5                   2.0                        9.0
6                   2.0                        9.0
7                   2.0                        5.0
8                   7.0                       10.0
9                   2.0                        0.0
Últimas 10 filas:
          id First_Name   Last_Name                       Email  \
49990  49991    Abigale     Weimann            will36@yahoo.com
49991  49992     Simeon    Johnston       frank_klein@gmail.com
49992  49993    Keshawn      Brekke   hettie.koelpin1@gmail.com
49993  49994      Effie       Nolan         josiane33@yahoo.com
49994  49995     Moriah      Casper         dangelo30@gmail.com
49995  49996    Bethany     Shields  rocky_mitchell@hotmail.com
49996  49997        Era  Swaniawski    dolores.roob@hotmail.com
49997  49998     Martin       Lakin   savanah.stracke@gmail.com
49998  49999      Aliya   Abernathy  vivienne.fritsch@yahoo.com
49999  50000    Coleman      Wisozk   abigayle.crooks@yahoo.com

                       Country Application_Date  YOE  Seniority  \
49990                  Belgium       2018-06-16   16  Mid-Level
49991  Cocos (Keeling) Islands       2022-03-09   30     Junior
49992                     Mali       2018-12-17    8       Lead
49993                Gibraltar       2019-11-10    6     Intern
49994                  Iceland       2019-04-20   15     Intern
49995       Dominican Republic       2022-01-09   27    Trainee
49996                  Morocco       2020-06-02   21       Lead
49997                   Uganda       2018-12-15   20    Trainee
49998           Czech Republic       2020-05-30   20     Senior
49999                    Palau       2022-06-13   15     Intern

                     Technology  Code_Challenge_Score  \
49990    Development - Frontend                   9.0
49991                  Security                   5.0
49992  Adobe Experience Manager                   1.0
49993                Salesforce                   4.0
49994                     Sales                   3.0
49995                  Security                   2.0
49996          Game Development                   1.0
49997     System Administration                   6.0
49998   Database Administration                   0.0
49999                  Mulesoft                   3.0

       Technical_Interview_Score
49990                        9.0
49991                        1.0
49992                        7.0
49993                        3.0
49994                        8.0
49995                        1.0
49996                        2.0
49997                        1.0
49998                        0.0
49999                        1.0
Primeras 10 filas ordenadas:
          id First_Name   Last_Name                           Email  \
49413  49414    Aaliyah    Botsford          aditya.bruen@gmail.com
48798  48799    Aaliyah       Boyer              zula97@hotmail.com
19489  19490    Aaliyah  Cartwright                 ole81@gmail.com
34356  34357    Aaliyah        Cole                hoyt85@gmail.com
49311  49312    Aaliyah       Emard       krystina.russel@yahoo.com
40425  40426    Aaliyah       Fahey  claudine_labadie83@hotmail.com
25256  25257    Aaliyah        Feil       gretchen.turner@gmail.com
25190  25191    Aaliyah   Gleichner          myra_green14@yahoo.com
18001  18002    Aaliyah   Greenholt            trevor77@hotmail.com
5314    5315    Aaliyah    Homenick              shawna58@gmail.com

                                     Country Application_Date  YOE Seniority  \
49413  Democratic People's Republic of Korea       2022-03-05    5      Lead
48798                      Equatorial Guinea       2021-01-12   27   Trainee
19489                                Finland       2022-07-01    0    Senior
34356                 Libyan Arab Jamahiriya       2019-10-16    8    Intern
49311                                Myanmar       2021-03-11    5    Junior
40425                             Mozambique       2021-10-08    8   Trainee
25256                              Lithuania       2019-01-08   25    Junior
25190                                Georgia       2020-03-09   10   Trainee
18001                             Mozambique       2020-06-06   13    Intern
5314                    United Arab Emirates       2020-08-14   22   Trainee

                                    Technology  Code_Challenge_Score  \
49413                               Salesforce                   4.0
48798                        Technical Writing                   7.0
19489                    Business Intelligence                   8.0
34356                   Development - Frontend                   3.0
49311                   Development - Frontend                   7.0
40425                         Game Development                   5.0
25256                               Salesforce                   6.0
25190                  Database Administration                   1.0
18001  Business Analytics / Project Management                  10.0
5314                     Development - Backend                   4.0

       Technical_Interview_Score
49413                        4.0
48798                        0.0
19489                        9.0
34356                        6.0
49311                        5.0
40425                        7.0
25256                        0.0
25190                        3.0
18001                        0.0
5314                         7.0
Últimas 10 filas ordenadas:
          id First_Name    Last_Name                        Email  \
17672  17673       Zula   Gusikowski    cheyanne_conn30@gmail.com
24216  24217       Zula      Hagenes            johan38@gmail.com
20496  20497       Zula        Haley        germaine6@hotmail.com
20277  20278       Zula       Hansen     billie.blick@hotmail.com
2706    2707       Zula      Keebler        francisco27@yahoo.com
30540  30541       Zula       Mayert             dave93@gmail.com
26163  26164       Zula      O'Keefe  maeve.kessler91@hotmail.com
28956  28957       Zula  Oberbrunner              trey3@yahoo.com
21337  21338       Zula      Stanton        lola_howell@yahoo.com
6669    6670       Zula         Veum           pattie92@gmail.com

                                    Country Application_Date  YOE  Seniority  \
17672                               Moldova       2018-03-20    4     Junior
24216                                Jordan       2018-05-23   26  Mid-Level
20496                              Pakistan       2020-10-24   15     Junior
20277                                 Macao       2020-03-03    0     Junior
2706                      Wallis and Futuna       2018-03-20   24  Mid-Level
30540                                Taiwan       2020-03-30    1     Intern
26163                               Armenia       2020-05-17   20  Mid-Level
28956                     Wallis and Futuna       2021-01-10    8  Architect
21337                               Lebanon       2020-02-23    0       Lead
6669   United States Minor Outlying Islands       2021-08-18   19     Junior

                                    Technology  Code_Challenge_Score  \
17672                    Development - Backend                   0.0
24216                                QA Manual                  10.0
20496                    Development - Backend                   6.0
20277  Business Analytics / Project Management                   9.0
2706                     System Administration                   8.0
30540                    Development - Backend                   1.0
26163                  Database Administration                   9.0
28956                        Technical Writing                   3.0
21337                      Security Compliance                   8.0
6669                            Client Success                   7.0

       Technical_Interview_Score
17672                        5.0
24216                        1.0
20496                        9.0
20277                        2.0
2706                         6.0
30540                        3.0
26163                        9.0
28956                        1.0
21337                        3.0
6669                         1.0

In [5]:
connection = mysql.connector.connect(**config)
print("Conexión exitosa a la base de datos")

# Crear un cursor para ejecutar consultas
cursor = connection.cursor()

# Ejecutar la consulta para obtener datos
query = "SELECT * FROM candidates"  # Reemplaza con tu consulta SQL
cursor.execute(query)

# Obtener los datos en un DataFrame de pandas
df = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])

print("Datos cargados en DataFrame:")
print(df.head())

# Agregar la columna 'contratado' basada en las condiciones
df['contratado'] = (df['Code_Challenge_Score'] >= 7) & (df['Technical_Interview_Score'] >= 7)
df['contratado'] = df['contratado'].map({True: 'Sí', False: 'No'})

# Mostrar el DataFrame con la nueva columna
print("DataFrame con la columna 'contratado':")
print(df.head())

Conexión exitosa a la base de datos
Datos cargados en DataFrame:
   id  First_Name   Last_Name                      Email  Country  \
0   1  Bernadette   Langworth        leonard91@yahoo.com   Norway
1   2      Camryn    Reynolds        zelda56@hotmail.com   Panama
2   3       Larue      Spinka   okey_schultz41@gmail.com  Belarus
3   4        Arch      Spinka     elvera_kulas@yahoo.com  Eritrea
4   5       Larue  Altenwerth  minnie.gislason@gmail.com  Myanmar

  Application_Date  YOE  Seniority                         Technology  \
0       2021-02-26    2     Intern                      Data Engineer
1       2021-09-09   10     Intern                      Data Engineer
2       2020-04-14    4  Mid-Level                     Client Success
3       2020-10-01   25    Trainee                          QA Manual
4       2020-05-20   13  Mid-Level  Social Media Community Management

   Code_Challenge_Score  Technical_Interview_Score
0                   3.0                        3.0
1                   2.0                       10.0
2                  10.0                        9.0
3                   7.0                        1.0
4                   9.0                        7.0
DataFrame con la columna 'contratado':
   id  First_Name   Last_Name                      Email  Country  \
0   1  Bernadette   Langworth        leonard91@yahoo.com   Norway
1   2      Camryn    Reynolds        zelda56@hotmail.com   Panama
2   3       Larue      Spinka   okey_schultz41@gmail.com  Belarus
3   4        Arch      Spinka     elvera_kulas@yahoo.com  Eritrea
4   5       Larue  Altenwerth  minnie.gislason@gmail.com  Myanmar

  Application_Date  YOE  Seniority                         Technology  \
0       2021-02-26    2     Intern                      Data Engineer
1       2021-09-09   10     Intern                      Data Engineer
2       2020-04-14    4  Mid-Level                     Client Success
3       2020-10-01   25    Trainee                          QA Manual
4       2020-05-20   13  Mid-Level  Social Media Community Management

   Code_Challenge_Score  Technical_Interview_Score contratado
0                   3.0                        3.0         No
1                   2.0                       10.0         No
2                  10.0                        9.0         Sí
3                   7.0                        1.0         No
4                   9.0                        7.0         Sí

Instalacion libreria extra

In [7]:
!pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading SQLAlchemy-2.0.32-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\josed\workshop1\.venv\lib\site-packages (from SQLAlchemy) (4.12.2)
Collecting greenlet!=0.4.17 (from SQLAlchemy)
  Downloading greenlet-3.0.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Downloading SQLAlchemy-2.0.32-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------------------ --------- 1.6/2.1 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 6.9 MB/s eta 0:00:00
Downloading greenlet-3.0.3-cp311-cp311-win_amd64.whl (292 kB)
Installing collected packages: greenlet, SQLAlchemy
Successfully installed SQLAlchemy-2.0.32 greenlet-3.0.3

Nueva Columna de Contratados ** No Tocar ni Ejecutar Mas **

In [11]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

try:
    # Establecer la conexión
    connection = mysql.connector.connect(**config)
    print("Conexión exitosa a la base de datos")

    # Crear un cursor para ejecutar consultas
    cursor = connection.cursor()

    # Ejecutar la consulta para obtener datos de la tabla original
    query = "SELECT * FROM candidates"
    cursor.execute(query)

    # Obtener los datos en un DataFrame de pandas
    df = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])

    # Eliminar la columna 'id' si existe
    if 'id' in df.columns:
        df = df.drop(columns=['id'])

    # Agregar la columna 'contratado' basada en las condiciones
    df['contratado'] = (df['Code_Challenge_Score'] >= 7) & (df['Technical_Interview_Score'] >= 7)
    df['contratado'] = df['contratado'].map({True: 'Sí', False: 'No'})

    # Crear una nueva conexión usando SQLAlchemy para insertar el DataFrame en MySQL
    engine = create_engine(f'mysql+mysqlconnector://{config["user"]}:{config["password"]}@{config["host"]}/{config["database"]}')

    # Insertar el DataFrame en la tabla `candidates_2`, sin la columna 'id'
    df.to_sql(name='candidates_2', con=engine, if_exists='append', index=False)

    print("Los datos han sido insertados en la tabla 'candidates_2' sin la columna 'id'.")

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("Conexión cerrada")

Conexión exitosa a la base de datos
Los datos han sido insertados en la tabla 'candidates_2' sin la columna 'id'.
Conexión cerrada

In [ ]:
# Cerrar la conexión
cursor.close()
db_connection.close()